apiVersion: batch/v1
kind: Job
metadata:
  name: helloworldtest
spec:
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 2400 # time to allow job to run
  template:
    metadata:
      labels:
        app: helloworldtest
        tier: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: helloworldtest
          image: 127.0.0.1:32000/helloworldtest:latest
