apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kaniko
      image: bitnami/kubectl:1.17
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      resources:
        requests:
          memory: "1Gi"
          cpu: "125m"
        limits:
          memory: "1Gi"
