apiVersion: v1
kind: Pod
metadata:
  name: helloworldtest
  labels:
    name: helloworldtest
spec:
  containers:
    - name: helloworldtest
      image: 127.0.0.1:32000/helloworldtest:latest
      env:
       - name: HELLO_URL
         value: "http://test-service"
