pipeline {
    agent any
    stages {
        stage('Undeploy Stage') {
            agent {
              kubernetes {
                label 'kubectl'
                idleMinutes 10
                yamlFile 'pods/kubectl-pod.yaml'
                defaultContainer 'kubectl'
              }
            }
            steps {
              sh "/usr/local/bin/kubectl delete --ignore-not-found=true -f desc/helloworld.yaml"
            }
        }
    }
}
